package main

func main () {
	//basics.Add(2,3)
	//basics.Pattern1()
	//basics.Pattern2()
	//basics.Odd(8)
	//basics.Even(8)
	//basics.FindMe(4)
	//basics.Array1()
	//basics.Array2()
	//basics.Array3()
	//basics.Array4()
	//basics.Slice1()
	//basics.Slice2()
	//basics.Slice3()
	//basics.Pointer1()
	//basics.Pointer2()
	//basics.VariadicSum()
	//basics.Factorial(5)
	//basics.RecursionPattern(5)
	//basics.Sorting()

	//advance.StructLibrary()
	//advance.Sorting()
	//advance.ReadFile1()
	//advance.ReadFile2()
	//advance.Write1()
	//advance.Write2()
	//advance.Map()
	//advance.MethodEx()
	//advance.InterfacesDemo()
	//advance.GoRoutine()
	//advance.ChannelWithBuffers()
	//advance.ChannelWithOutBuffers()

}
